image: Unbunu1804 # образ для сборки
stack: node 12 # окружение
branches:
  only:
    - master # ветка git
cahe: node_modules # откуда кеширование
install:
  - npm install # команда установки зависимостей
build: off #не используется сборка
test_scipt:
  - npm run lint && npm test # скрипт сборки
  
